version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "FluentAssertions"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.NET.Sdk.Functions"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.DependencyInjection"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Logging.Console"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.Extensions.Configuration.UserSecrets"
        update-types: ["version-update:semver-major"]
    groups:
      xunit:
        patterns:
          - xunit
          - xunit.analyzers
