name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - deploy.ps1
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - deploy.ps1
      - LICENSE
      - README.md
env:
  BUILD_CONFIGURATION: Release
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Restore NuGet packages
        run: dotnet restore
      - name: Dotnet format
        run: dotnet format --verify-no-changes
      - name: Build
        run: dotnet build --configuration ${BUILD_CONFIGURATION} --no-restore
      - name: Test
        run: dotnet test --configuration ${BUILD_CONFIGURATION} --no-build
