name: Build
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - deploy.ps1
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.vscode/**'
      - 'deploy/**'
      - 'docs/**'
      - deploy.ps1
      - LICENSE
      - README.md

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build
        run: ./build.sh
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: './artifacts/test-results/**/*.trx'
          if-no-files-found: error
